package analytics

import (
	"testing"

	"github.com/asenawritescode/kora/doctype"
)

// buildTestDocType creates a minimal DocType for testing metric generation.
func buildTestDocType(name string, isSubmittable bool, fields ...doctype.Field) *doctype.DocType {
	return &doctype.DocType{
		Name:          name,
		IsSubmittable: isSubmittable,
		Fields:        fields,
	}
}

func field(name, ftype, label string, inList bool) doctype.Field {
	return doctype.Field{
		Fieldname:   name,
		Fieldtype:   ftype,
		Label:       label,
		InListView:  inList,
	}
}

func TestGenerateMetrics_EveryDocType_Count(t *testing.T) {
	dt := buildTestDocType("Customer", false,
		field("name", "Data", "Name", true),
	)

	metrics := GenerateMetrics(dt)

	// Every DocType gets a count metric.
	found := false
	for _, m := range metrics {
		if m.Name == "customer_count" && m.Type == MetricCount {
			found = true
			if !m.AutoGenerated {
				t.Error("count metric should be auto-generated")
			}
		}
	}
	if !found {
		t.Error("expected customer_count metric")
	}
}

func TestGenerateMetrics_EveryDocType_CreatedDaily(t *testing.T) {
	dt := buildTestDocType("Work Order", false,
		field("title", "Data", "Title", true),
	)

	metrics := GenerateMetrics(dt)

	for _, m := range metrics {
		if m.Name == "work_order_created_daily" {
			if m.Type != MetricCountByTime {
				t.Errorf("expected MetricCountByTime, got %s", m.Type)
			}
			if m.TimeField != "creation" {
				t.Errorf("expected time_field='creation', got %q", m.TimeField)
			}
			return
		}
	}
	t.Error("expected work_order_created_daily metric")
}

func TestGenerateMetrics_SelectField_CountByField(t *testing.T) {
	dt := buildTestDocType("Customer", false,
		field("status", "Select", "Status", true),
	)

	metrics := GenerateMetrics(dt)

	found := false
	for _, m := range metrics {
		if m.Name == "customer_count_by_status" {
			found = true
			if m.Type != MetricCountByField {
				t.Errorf("expected MetricCountByField, got %s", m.Type)
			}
			if m.Field != "status" {
				t.Errorf("expected field='status', got %q", m.Field)
			}
		}
	}
	if !found {
		t.Error("expected customer_count_by_status metric for Select field")
	}
}

func TestGenerateMetrics_IntField_Sum(t *testing.T) {
	dt := buildTestDocType("Invoice", false,
		field("total", "Int", "Total", true),
	)

	metrics := GenerateMetrics(dt)

	found := false
	for _, m := range metrics {
		if m.Name == "invoice_sum_total" {
			found = true
			if m.Type != MetricSum {
				t.Errorf("expected MetricSum, got %s", m.Type)
			}
		}
	}
	if !found {
		t.Error("expected invoice_sum_total metric for Int field")
	}
}

func TestGenerateMetrics_CurrencyField_Sum(t *testing.T) {
	dt := buildTestDocType("Invoice", false,
		field("amount", "Currency", "Amount", true),
	)

	metrics := GenerateMetrics(dt)

	for _, m := range metrics {
		if m.Name == "invoice_sum_amount" && m.Type == MetricSum {
			return
		}
	}
	t.Error("expected sum metric for Currency field")
}

func TestGenerateMetrics_LinkField_CountByField(t *testing.T) {
	dt := buildTestDocType("Work Order", false,
		field("customer", "Link", "Customer", true),
	)

	metrics := GenerateMetrics(dt)

	for _, m := range metrics {
		if m.Name == "work_order_count_by_customer" && m.Type == MetricCountByField {
			return
		}
	}
	t.Error("expected count_by_field metric for Link field")
}

func TestGenerateMetrics_IsSubmittable_StateDistribution(t *testing.T) {
	dt := buildTestDocType("Work Order", true,
		field("title", "Data", "Title", true),
	)

	metrics := GenerateMetrics(dt)

	found := false
	for _, m := range metrics {
		if m.Name == "work_order_state_distribution" {
			found = true
			if m.Type != MetricStateDistribution {
				t.Errorf("expected MetricStateDistribution, got %s", m.Type)
			}
		}
	}
	if !found {
		t.Error("expected state_distribution metric for submittable doctype")
	}
}

func TestGenerateMetrics_NotSubmittable_NoStateDistribution(t *testing.T) {
	dt := buildTestDocType("Note", false,
		field("content", "Text", "Content", false),
	)

	metrics := GenerateMetrics(dt)

	for _, m := range metrics {
		if m.Type == MetricStateDistribution {
			t.Error("non-submittable doctype should not have state_distribution")
		}
	}
}

func TestGenerateMetrics_SkipsLayoutFields(t *testing.T) {
	dt := buildTestDocType("Customer", false,
		field("name", "Data", "Name", true),
		field("spacer", "Section Break", "", false),
		field("col", "Column Break", "", false),
		field("heading", "Heading", "", false),
		field("items", "Table", "Items", false),
	)

	metrics := GenerateMetrics(dt)

	// Should NOT have metrics for layout/table fields.
	for _, m := range metrics {
		if m.Field == "spacer" || m.Field == "col" || m.Field == "heading" || m.Field == "items" {
			t.Errorf("should not generate metric for layout/table field %q", m.Field)
		}
	}
}

func TestGenerateMetrics_MultipleNumericFields(t *testing.T) {
	dt := buildTestDocType("Invoice", false,
		field("subtotal", "Float", "Subtotal", true),
		field("tax", "Currency", "Tax", true),
		field("discount", "Percent", "Discount", true),
	)

	metrics := GenerateMetrics(dt)

	sumCount := 0
	for _, m := range metrics {
		if m.Type == MetricSum {
			sumCount++
		}
	}
	if sumCount != 3 {
		t.Errorf("expected 3 sum metrics for 3 numeric fields, got %d", sumCount)
	}
}

func TestMetricName(t *testing.T) {
	tests := []struct{ input, expected string }{
		{"Work Order", "work_order"},
		{"Customer", "customer"},
		{"estimated_hours", "estimated_hours"},
		{"Total Amount", "total_amount"},
	}
	for _, tc := range tests {
		got := metricName(tc.input)
		if got != tc.expected {
			t.Errorf("metricName(%q) = %q, want %q", tc.input, got, tc.expected)
		}
	}
}

func TestGenerateWorkflowMetrics(t *testing.T) {
	dt := buildTestDocType("Work Order", true)
	wf := &doctype.Workflow{
		Name:         "Work Order Lifecycle",
		DocumentType: "Work Order",
		Transitions: []doctype.WorkflowTransition{
			{Action: "Submit", From: "Draft", To: "Submitted"},
			{Action: "Approve", From: "Submitted", To: "Approved"},
			{Action: "Complete", From: "Approved", To: "Completed"},
		},
	}

	metrics := GenerateWorkflowMetrics(dt, wf)

	if len(metrics) != 3 {
		t.Fatalf("expected 3 transition metrics, got %d", len(metrics))
	}

	// Check naming pattern: <doctype>_avg_<from>_to_<to>_time
	expected := map[string]bool{
		"work_order_avg_draft_to_submitted_time":    false,
		"work_order_avg_submitted_to_approved_time": false,
		"work_order_avg_approved_to_completed_time": false,
	}
	for _, m := range metrics {
		if _, ok := expected[m.Name]; ok {
			expected[m.Name] = true
		}
		if !m.AutoGenerated {
			t.Errorf("workflow metric %s should be auto-generated", m.Name)
		}
	}
	for name, found := range expected {
		if !found {
			t.Errorf("expected workflow metric %s", name)
		}
	}
}

func TestGenerateWorkflowMetrics_NilWorkflow(t *testing.T) {
	dt := buildTestDocType("Customer", false)
	metrics := GenerateWorkflowMetrics(dt, nil)
	if len(metrics) != 0 {
		t.Errorf("nil workflow should return 0 metrics, got %d", len(metrics))
	}
}
