package analytics

import (
	"fmt"
	"strings"

	"github.com/asenawritescode/kora/doctype"
)

// MetricType enumerates how a metric is computed.
type MetricType string

const (
	MetricCount            MetricType = "count"
	MetricCountByField     MetricType = "count_by_field"
	MetricCountByTime      MetricType = "count_by_time"
	MetricSum              MetricType = "sum"
	MetricAvg              MetricType = "avg"
	MetricStateDistribution MetricType = "state_distribution"
	MetricCountByLinkedField MetricType = "count_by_linked_field"
)

// Metric defines a single analytics metric — either auto-generated from DocType
// metadata or user-defined via YAML / admin UI.
type Metric struct {
	Name        string     `json:"name" yaml:"name"`
	Label       string     `json:"label" yaml:"label"`
	Type        MetricType `json:"type" yaml:"type"`
	DocType     string     `json:"doctype" yaml:"doctype"`
	Field       string     `json:"field,omitempty" yaml:"field,omitempty"`               // for count_by_field, sum, avg
	LinkField   string     `json:"link_field,omitempty" yaml:"link_field,omitempty"`     // for count_by_linked_field
	GroupByField string    `json:"group_by_field,omitempty" yaml:"group_by_field,omitempty"` // for count_by_linked_field
	TimeField   string     `json:"time_field,omitempty" yaml:"time_field,omitempty"`     // for count_by_time
	Filters     []MetricFilter `json:"filters,omitempty" yaml:"filters,omitempty"`
	AutoGenerated bool     `json:"auto_generated" yaml:"auto_generated"` // true if generated from DocType metadata
}

// MetricFilter is a simple field=value filter on a metric.
type MetricFilter struct {
	Field    string `json:"field" yaml:"field"`
	Operator string `json:"op" yaml:"op"`
	Value    string `json:"value" yaml:"value"`
}

// GenerateMetrics produces baseline metrics for a DocType from its field metadata.
// These are the "Level 0" metrics that appear on the Insights tab with zero config.
func GenerateMetrics(dt *doctype.DocType) []*Metric {
	var metrics []*Metric

	name := dt.Name
	safeName := metricName(name)

	// Every DocType gets a count and a creation trend.
	metrics = append(metrics,
		&Metric{
			Name:         safeName + "_count",
			Label:        name + " Count",
			Type:         MetricCount,
			DocType:      name,
			AutoGenerated: true,
		},
		&Metric{
			Name:         safeName + "_created_daily",
			Label:        name + " Created (Daily)",
			Type:         MetricCountByTime,
			DocType:      name,
			TimeField:    "creation",
			AutoGenerated: true,
		},
	)

	// For every Select field: generate a count_by_field metric.
	// For every numeric field: generate a sum metric.
	// For every Link field: generate a count_by_field metric (count by linked doc name).
	// Layout-only fields (Section Break, Column Break, Heading) are skipped.
	for _, f := range dt.Fields {
		if f.IsLayoutField() || f.Fieldtype == "Table" {
			continue
		}

		switch f.Fieldtype {
		case "Select":
			metrics = append(metrics, &Metric{
				Name:         safeName + "_count_by_" + metricName(f.Fieldname),
				Label:        name + " by " + f.Label,
				Type:         MetricCountByField,
				DocType:      name,
				Field:        f.Fieldname,
				AutoGenerated: true,
			})

		case "Link", "Dynamic Link":
			metrics = append(metrics, &Metric{
				Name:         safeName + "_count_by_" + metricName(f.Fieldname),
				Label:        name + " by " + f.Label,
				Type:         MetricCountByField,
				DocType:      name,
				Field:        f.Fieldname,
				AutoGenerated: true,
			})

		case "Int", "Float", "Currency", "Percent":
			metrics = append(metrics, &Metric{
				Name:         safeName + "_sum_" + metricName(f.Fieldname),
				Label:        "Total " + f.Label,
				Type:         MetricSum,
				DocType:      name,
				Field:        f.Fieldname,
				AutoGenerated: true,
			})
		}
	}

	// If the DocType has a workflow, add state distribution.
	// The workflow check is done at registration time — we just check IsSubmittable.
	if dt.IsSubmittable {
		metrics = append(metrics, &Metric{
			Name:         safeName + "_state_distribution",
			Label:        name + " by State",
			Type:         MetricStateDistribution,
			DocType:      name,
			AutoGenerated: true,
		})
	}

	return metrics
}

// metricName converts a display name to a safe metric identifier.
// "Work Order" → "work_order", "estimated_hours" → "estimated_hours"
func metricName(s string) string {
	return strings.ToLower(strings.ReplaceAll(s, " ", "_"))
}

// GenerateWorkflowMetrics produces metrics for a DocType with a workflow.
// These are separate from GenerateMetrics because they require the workflow definition.
func GenerateWorkflowMetrics(dt *doctype.DocType, wf *doctype.Workflow) []*Metric {
	if wf == nil || len(wf.Transitions) == 0 {
		return nil
	}

	safeName := metricName(dt.Name)
	var metrics []*Metric

	// For each named transition, generate an avg_duration metric.
	seen := make(map[string]bool)
	for _, t := range wf.Transitions {
		key := t.From + "→" + t.To
		if seen[key] {
			continue
		}
		seen[key] = true

		metrics = append(metrics, &Metric{
			Name:         fmt.Sprintf("%s_avg_%s_to_%s_time", safeName, metricName(t.From), metricName(t.To)),
			Label:        fmt.Sprintf("Avg Time: %s → %s", t.From, t.To),
			Type:         MetricAvg,
			DocType:      dt.Name,
			AutoGenerated: true,
		})
	}

	return metrics
}
