- doctype: Campaign
  role: Marketing Campaigns Operator
  can_read: true
  can_write: true
  can_create: true
  can_delete: false
  can_submit: true
- doctype: Campaign
  role: Marketing Campaigns Reviewer
  can_read: true
  can_write: true
  can_create: false
  can_delete: false
  can_submit: true
- doctype: Campaign
  role: Marketing Campaigns Administrator
  can_read: true
  can_write: true
  can_create: true
  can_delete: true
  can_submit: true
- doctype: Audience
  role: Marketing Campaigns Operator
  can_read: true
  can_write: true
  can_create: true
  can_delete: false
- doctype: Channel Message
  role: Marketing Campaigns Reviewer
  can_read: true
  can_write: true
  can_create: true
  can_delete: false
