name: Internal Requests and Approvals Workflow
document_type: Internal Request
is_active: true
workflow_state_field: status

states:
  - state: draft
    doc_status: 0
    allow_edit: Internal Requests and Approvals Operator, Internal Requests and Approvals Administrator
    style: default
  - state: submitted
    doc_status: 0
    allow_edit: Internal Requests and Approvals Reviewer, Internal Requests and Approvals Administrator
    style: info
  - state: triaged
    doc_status: 0
    allow_edit: Internal Requests and Approvals Reviewer, Internal Requests and Approvals Administrator
    style: info
  - state: pending_approval
    doc_status: 0
    allow_edit: Internal Requests and Approvals Reviewer, Internal Requests and Approvals Administrator
    style: info
  - state: approved
    doc_status: 0
    allow_edit: Internal Requests and Approvals Reviewer, Internal Requests and Approvals Administrator
    style: info
  - state: fulfilled
    doc_status: 0
    allow_edit: Internal Requests and Approvals Reviewer, Internal Requests and Approvals Administrator
    style: info
  - state: exception
    doc_status: 1
    allow_edit: Internal Requests and Approvals Reviewer, Internal Requests and Approvals Administrator
    style: success

transitions:
  - action: Advance
    from: draft
    to: submitted
    allowed: Internal Requests and Approvals Operator, Internal Requests and Approvals Reviewer, Internal Requests and Approvals Administrator
  - action: Advance
    from: submitted
    to: triaged
    allowed: Internal Requests and Approvals Operator, Internal Requests and Approvals Reviewer, Internal Requests and Approvals Administrator
  - action: Advance
    from: triaged
    to: pending_approval
    allowed: Internal Requests and Approvals Operator, Internal Requests and Approvals Reviewer, Internal Requests and Approvals Administrator
  - action: Advance
    from: pending_approval
    to: approved
    allowed: Internal Requests and Approvals Operator, Internal Requests and Approvals Reviewer, Internal Requests and Approvals Administrator
  - action: Advance
    from: approved
    to: fulfilled
    allowed: Internal Requests and Approvals Operator, Internal Requests and Approvals Reviewer, Internal Requests and Approvals Administrator
  - action: Advance
    from: fulfilled
    to: exception
    allowed: Internal Requests and Approvals Operator, Internal Requests and Approvals Reviewer, Internal Requests and Approvals Administrator
