- doctype: Student
  role: School Administrator
  can_read: true
  can_write: true
  can_create: true
  can_delete: false
- doctype: Student
  role: Teacher
  can_read: true
  can_write: false
  can_create: false
  can_delete: false
- doctype: Student
  role: Administrator
  can_read: true
  can_write: true
  can_create: true
  can_delete: true
- doctype: Class
  role: School Administrator
  can_read: true
  can_write: true
  can_create: true
  can_delete: false
- doctype: Class
  role: Teacher
  can_read: true
  can_write: false
  can_create: false
  can_delete: false
- doctype: Class
  role: Administrator
  can_read: true
  can_write: true
  can_create: true
  can_delete: true
- doctype: Attendance
  role: School Administrator
  can_read: true
  can_write: true
  can_create: true
  can_delete: false
- doctype: Attendance
  role: Teacher
  can_read: true
  can_write: true
  can_create: true
  can_delete: false
- doctype: Attendance
  role: Administrator
  can_read: true
  can_write: true
  can_create: true
  can_delete: true
- doctype: Assessment
  role: School Administrator
  can_read: true
  can_write: true
  can_create: true
  can_delete: false
- doctype: Assessment
  role: Teacher
  can_read: true
  can_write: true
  can_create: true
  can_delete: false
- doctype: Assessment
  role: Administrator
  can_read: true
  can_write: true
  can_create: true
  can_delete: true
