- doctype: Inspection Request
  role: Quality Management Operator
  can_read: true
  can_write: true
  can_create: true
  can_delete: false
  can_submit: true
- doctype: Inspection Request
  role: Quality Management Reviewer
  can_read: true
  can_write: true
  can_create: false
  can_delete: false
  can_submit: true
- doctype: Inspection Request
  role: Quality Management Administrator
  can_read: true
  can_write: true
  can_create: true
  can_delete: true
  can_submit: true
- doctype: Nonconformance
  role: Quality Management Operator
  can_read: true
  can_write: true
  can_create: true
  can_delete: false
- doctype: Corrective Action
  role: Quality Management Reviewer
  can_read: true
  can_write: true
  can_create: true
  can_delete: false
