name: Manufacturing Order
module: Light Manufacturing
is_submittable: true
title_field: reference
fields:
  - fieldname: reference
    fieldtype: Data
    label: Reference
    reqd: true
    unique: true
  - fieldname: assignee
    fieldtype: Data
    label: Assignee
  - fieldname: status
    fieldtype: Data
    label: Status
    default: planned
    read_only: true
