name: Light Manufacturing Workflow
document_type: Manufacturing Order
is_active: true
workflow_state_field: status

states:
  - state: planned
    doc_status: 0
    allow_edit: Light Manufacturing Operator, Light Manufacturing Administrator
    style: default
  - state: released
    doc_status: 0
    allow_edit: Light Manufacturing Reviewer, Light Manufacturing Administrator
    style: info
  - state: in_progress
    doc_status: 0
    allow_edit: Light Manufacturing Reviewer, Light Manufacturing Administrator
    style: info
  - state: inspected
    doc_status: 0
    allow_edit: Light Manufacturing Reviewer, Light Manufacturing Administrator
    style: info
  - state: completed
    doc_status: 0
    allow_edit: Light Manufacturing Reviewer, Light Manufacturing Administrator
    style: info
  - state: cancelled
    doc_status: 1
    allow_edit: Light Manufacturing Reviewer, Light Manufacturing Administrator
    style: success

transitions:
  - action: Advance
    from: planned
    to: released
    allowed: Light Manufacturing Operator, Light Manufacturing Reviewer, Light Manufacturing Administrator
  - action: Advance
    from: released
    to: in_progress
    allowed: Light Manufacturing Operator, Light Manufacturing Reviewer, Light Manufacturing Administrator
  - action: Advance
    from: in_progress
    to: inspected
    allowed: Light Manufacturing Operator, Light Manufacturing Reviewer, Light Manufacturing Administrator
  - action: Advance
    from: inspected
    to: completed
    allowed: Light Manufacturing Operator, Light Manufacturing Reviewer, Light Manufacturing Administrator
  - action: Advance
    from: completed
    to: cancelled
    allowed: Light Manufacturing Operator, Light Manufacturing Reviewer, Light Manufacturing Administrator
