name: Distributor Order
module: Wholesale and Distribution
is_submittable: true
title_field: reference
fields:
  - fieldname: reference
    fieldtype: Data
    label: Reference
    reqd: true
    unique: true
  - fieldname: assignee
    fieldtype: Data
    label: Assignee
  - fieldname: status
    fieldtype: Data
    label: Status
    default: draft
    read_only: true
