- doctype: Expense Claim
  role: Expense and Reimbursement Operator
  can_read: true
  can_write: true
  can_create: true
  can_delete: false
  can_submit: true
- doctype: Expense Claim
  role: Expense and Reimbursement Reviewer
  can_read: true
  can_write: true
  can_create: false
  can_delete: false
  can_submit: true
- doctype: Expense Claim
  role: Expense and Reimbursement Administrator
  can_read: true
  can_write: true
  can_create: true
  can_delete: true
  can_submit: true
- doctype: Expense Line
  role: Expense and Reimbursement Operator
  can_read: true
  can_write: true
  can_create: true
  can_delete: false
- doctype: Receipt
  role: Expense and Reimbursement Reviewer
  can_read: true
  can_write: true
  can_create: true
  can_delete: false
