name: Expense Line
module: Expense and Reimbursement
title_field: reference
search_fields: reference, status
fields:
  - fieldname: reference
    fieldtype: Data
    label: Reference
    reqd: true
    in_list_view: true
  - fieldname: source_record
    fieldtype: Data
    label: Primary Record
    reqd: true
  - fieldname: actor
    fieldtype: Data
    label: Actor
    reqd: true
  - fieldname: details
    fieldtype: Text
    label: Details
  - fieldname: status
    fieldtype: Data
    label: Status
    default: Draft
    in_list_view: true
