name: Pharmacy and Medical Inventory Workflow
document_type: Dispense Request
is_active: true
workflow_state_field: status

states:
  - state: received
    doc_status: 0
    allow_edit: Pharmacy and Medical Inventory Operator, Pharmacy and Medical Inventory Administrator
    style: default
  - state: verified
    doc_status: 0
    allow_edit: Pharmacy and Medical Inventory Reviewer, Pharmacy and Medical Inventory Administrator
    style: info
  - state: dispensed
    doc_status: 0
    allow_edit: Pharmacy and Medical Inventory Reviewer, Pharmacy and Medical Inventory Administrator
    style: info
  - state: returned
    doc_status: 0
    allow_edit: Pharmacy and Medical Inventory Reviewer, Pharmacy and Medical Inventory Administrator
    style: info
  - state: recalled
    doc_status: 1
    allow_edit: Pharmacy and Medical Inventory Reviewer, Pharmacy and Medical Inventory Administrator
    style: success

transitions:
  - action: Advance
    from: received
    to: verified
    allowed: Pharmacy and Medical Inventory Operator, Pharmacy and Medical Inventory Reviewer, Pharmacy and Medical Inventory Administrator
  - action: Advance
    from: verified
    to: dispensed
    allowed: Pharmacy and Medical Inventory Operator, Pharmacy and Medical Inventory Reviewer, Pharmacy and Medical Inventory Administrator
  - action: Advance
    from: dispensed
    to: returned
    allowed: Pharmacy and Medical Inventory Operator, Pharmacy and Medical Inventory Reviewer, Pharmacy and Medical Inventory Administrator
  - action: Advance
    from: returned
    to: recalled
    allowed: Pharmacy and Medical Inventory Operator, Pharmacy and Medical Inventory Reviewer, Pharmacy and Medical Inventory Administrator
