name: Purchasing Workflow
document_type: Purchase Request
is_active: true
workflow_state_field: status
states:
  - state: Draft
    doc_status: 0
    allow_edit: Purchasing Operator, Purchasing Administrator
    style: default
  - state: Submitted
    doc_status: 0
    allow_edit: Purchasing Reviewer, Purchasing Administrator
    style: info
  - state: Approved
    doc_status: 0
    allow_edit: Purchasing Reviewer, Purchasing Administrator
    style: success
  - state: Ordered
    doc_status: 1
    allow_edit: ""
    style: success
transitions:
  - action: Submit
    from: Draft
    to: Submitted
    allowed: Purchasing Operator, Purchasing Administrator
  - action: Approve
    from: Submitted
    to: Approved
    allowed: Purchasing Reviewer, Purchasing Administrator
  - action: Order
    from: Approved
    to: Ordered
    allowed: Purchasing Reviewer, Purchasing Administrator
