package doctype

import (
	"encoding/json"
	"strings"
)

// AnalyticsMetricConfig is the config-level representation of an analytics metric,
// stored in ConfigSnapshot for versioning. Mirrors _kora_analytics_metric columns.
type AnalyticsMetricConfig struct {
	Name          string `json:"name"`
	Label         string `json:"label"`
	Type          string `json:"type"`
	DocType       string `json:"doctype"`
	FieldName     string `json:"field_name,omitempty"`
	LinkField     string `json:"link_field,omitempty"`
	GroupByField  string `json:"group_by_field,omitempty"`
	AutoGenerated bool   `json:"auto_generated"`
}

// ScriptSnapshot is the versioned representation of a script, stored in config snapshots.
// It captures enough information to identify and restore the script without storing the full body
// (the full body is in _kora_script and can be looked up by name+hash).
type ScriptSnapshot struct {
	Name          string `json:"name"`
	ScriptType    string `json:"script_type"`
	DocType       string `json:"doctype,omitempty"`
	Event         string `json:"event,omitempty"`
	MethodPath    string `json:"method_path,omitempty"`
	WorkflowAction string `json:"workflow_action,omitempty"`
	Schedule      string `json:"schedule,omitempty"`
	Priority      int    `json:"priority"`
	IsActive      bool   `json:"is_active"`
	RunAs         string `json:"run_as,omitempty"`
	TimeoutMs     int    `json:"timeout_ms"`
	ScriptHash    string `json:"script_hash"` // SHA-256 of script body
}

// ConfigSnapshot is the complete configuration state stored in _kora_config_version.config.
// It replaces the doctypes-only JSON array with a versioned snapshot of every config entity.
type ConfigSnapshot struct {
	DocTypes         []*DocType               `json:"doctypes"`
	Roles            []*Role                  `json:"roles"`
	Permissions      []*Permission            `json:"permissions"`
	Workflows        []*Workflow              `json:"workflows"`
	AnalyticsMetrics []*AnalyticsMetricConfig `json:"analytics_metrics,omitempty"`
	Scripts          []*ScriptSnapshot        `json:"scripts,omitempty"`
}

// ParseSnapshot parses a config snapshot from stored JSON, handling both:
//   - Old format: [...] (JSON array of doctypes only)
//   - New format: {"doctypes":[...], "roles":[...], ...}
func ParseSnapshot(configJSON string) (*ConfigSnapshot, error) {
	trimmed := strings.TrimSpace(configJSON)
	if strings.HasPrefix(trimmed, "[") {
		// Old format: array of doctypes only.
		var doctypes []*DocType
		if err := json.Unmarshal([]byte(configJSON), &doctypes); err != nil {
			return nil, err
		}
		return &ConfigSnapshot{DocTypes: doctypes}, nil
	}

	// New format: full ConfigSnapshot.
	var snapshot ConfigSnapshot
	if err := json.Unmarshal([]byte(configJSON), &snapshot); err != nil {
		return nil, err
	}
	return &snapshot, nil
}
