package doctype

import (
	"encoding/json"
	"strings"
)

// AnalyticsMetricConfig is the config-level representation of an analytics metric,
// stored in ConfigSnapshot for versioning. Mirrors _kora_analytics_metric columns.
type AnalyticsMetricConfig struct {
	Name          string `json:"name"`
	Label         string `json:"label"`
	Type          string `json:"type"`
	DocType       string `json:"doctype"`
	FieldName     string `json:"field_name,omitempty"`
	LinkField     string `json:"link_field,omitempty"`
	GroupByField  string `json:"group_by_field,omitempty"`
	AutoGenerated bool   `json:"auto_generated"`
}

// ConfigSnapshot is the complete configuration state stored in _kora_config_version.config.
// It replaces the doctypes-only JSON array with a versioned snapshot of every config entity.
type ConfigSnapshot struct {
	DocTypes         []*DocType               `json:"doctypes"`
	Roles            []*Role                  `json:"roles"`
	Permissions      []*Permission            `json:"permissions"`
	Workflows        []*Workflow              `json:"workflows"`
	AnalyticsMetrics []*AnalyticsMetricConfig `json:"analytics_metrics,omitempty"`
}

// ParseSnapshot parses a config snapshot from stored JSON, handling both:
//   - Old format: [...] (JSON array of doctypes only)
//   - New format: {"doctypes":[...], "roles":[...], ...}
func ParseSnapshot(configJSON string) (*ConfigSnapshot, error) {
	trimmed := strings.TrimSpace(configJSON)
	if strings.HasPrefix(trimmed, "[") {
		// Old format: array of doctypes only.
		var doctypes []*DocType
		if err := json.Unmarshal([]byte(configJSON), &doctypes); err != nil {
			return nil, err
		}
		return &ConfigSnapshot{DocTypes: doctypes}, nil
	}

	// New format: full ConfigSnapshot.
	var snapshot ConfigSnapshot
	if err := json.Unmarshal([]byte(configJSON), &snapshot); err != nil {
		return nil, err
	}
	return &snapshot, nil
}
