name: Budgeting and Management Reporting Workflow
document_type: Budget
is_active: true
workflow_state_field: status

states:
  - state: draft
    doc_status: 0
    allow_edit: Budgeting and Management Reporting Operator, Budgeting and Management Reporting Administrator
    style: default
  - state: submitted
    doc_status: 0
    allow_edit: Budgeting and Management Reporting Reviewer, Budgeting and Management Reporting Administrator
    style: info
  - state: approved
    doc_status: 0
    allow_edit: Budgeting and Management Reporting Reviewer, Budgeting and Management Reporting Administrator
    style: info
  - state: active
    doc_status: 0
    allow_edit: Budgeting and Management Reporting Reviewer, Budgeting and Management Reporting Administrator
    style: info
  - state: closed
    doc_status: 1
    allow_edit: Budgeting and Management Reporting Reviewer, Budgeting and Management Reporting Administrator
    style: success

transitions:
  - action: Advance
    from: draft
    to: submitted
    allowed: Budgeting and Management Reporting Operator, Budgeting and Management Reporting Reviewer, Budgeting and Management Reporting Administrator
  - action: Advance
    from: submitted
    to: approved
    allowed: Budgeting and Management Reporting Operator, Budgeting and Management Reporting Reviewer, Budgeting and Management Reporting Administrator
  - action: Advance
    from: approved
    to: active
    allowed: Budgeting and Management Reporting Operator, Budgeting and Management Reporting Reviewer, Budgeting and Management Reporting Administrator
  - action: Advance
    from: active
    to: closed
    allowed: Budgeting and Management Reporting Operator, Budgeting and Management Reporting Reviewer, Budgeting and Management Reporting Administrator
