name: E-commerce and Order Fulfillment Workflow
document_type: Web Order
is_active: true
workflow_state_field: status

states:
  - state: created
    doc_status: 0
    allow_edit: E-commerce and Order Fulfillment Operator, E-commerce and Order Fulfillment Administrator
    style: default
  - state: paid
    doc_status: 0
    allow_edit: E-commerce and Order Fulfillment Reviewer, E-commerce and Order Fulfillment Administrator
    style: info
  - state: allocated
    doc_status: 0
    allow_edit: E-commerce and Order Fulfillment Reviewer, E-commerce and Order Fulfillment Administrator
    style: info
  - state: packed
    doc_status: 0
    allow_edit: E-commerce and Order Fulfillment Reviewer, E-commerce and Order Fulfillment Administrator
    style: info
  - state: shipped
    doc_status: 0
    allow_edit: E-commerce and Order Fulfillment Reviewer, E-commerce and Order Fulfillment Administrator
    style: info
  - state: delivered
    doc_status: 0
    allow_edit: E-commerce and Order Fulfillment Reviewer, E-commerce and Order Fulfillment Administrator
    style: info
  - state: returned
    doc_status: 1
    allow_edit: E-commerce and Order Fulfillment Reviewer, E-commerce and Order Fulfillment Administrator
    style: success

transitions:
  - action: Advance
    from: created
    to: paid
    allowed: E-commerce and Order Fulfillment Operator, E-commerce and Order Fulfillment Reviewer, E-commerce and Order Fulfillment Administrator
  - action: Advance
    from: paid
    to: allocated
    allowed: E-commerce and Order Fulfillment Operator, E-commerce and Order Fulfillment Reviewer, E-commerce and Order Fulfillment Administrator
  - action: Advance
    from: allocated
    to: packed
    allowed: E-commerce and Order Fulfillment Operator, E-commerce and Order Fulfillment Reviewer, E-commerce and Order Fulfillment Administrator
  - action: Advance
    from: packed
    to: shipped
    allowed: E-commerce and Order Fulfillment Operator, E-commerce and Order Fulfillment Reviewer, E-commerce and Order Fulfillment Administrator
  - action: Advance
    from: shipped
    to: delivered
    allowed: E-commerce and Order Fulfillment Operator, E-commerce and Order Fulfillment Reviewer, E-commerce and Order Fulfillment Administrator
  - action: Advance
    from: delivered
    to: returned
    allowed: E-commerce and Order Fulfillment Operator, E-commerce and Order Fulfillment Reviewer, E-commerce and Order Fulfillment Administrator
