import React, { type ComponentType, type HTMLAttributes, type ReactNode } from 'react'

type Variant = 'default' | 'primary' | 'secondary' | 'outline' | 'ghost' | 'destructive' | 'blue' | 'teal' | 'neutral' | 'warning'
const cn = (...values: Array<string | number | undefined | false>) => values.filter(Boolean).join(' ')

export function Theme({ children }: { children: ReactNode }) { return <>{children}</> }
export function LinkProvider({ children }: { children: ReactNode; component?: ComponentType<any> }) { return <>{children}</> }
export function AppShell({ children, topNav, sideNav }: { children: ReactNode; topNav?: ReactNode; sideNav?: ReactNode; variant?: string; height?: string; contentPadding?: number }) { return <div className="kora-cloud-shell"><header>{topNav}</header><div className="kora-cloud-body"><aside className="kora-cloud-nav">{sideNav}</aside><div>{children}</div></div></div> }
export function SideNav({ children, header }: { children: ReactNode; header?: ReactNode; collapsible?: unknown }) { return <nav>{header}{children}</nav> }
export function SideNavHeading({ heading, subheading }: { heading: string; subheading?: string }) { return <div className="kora-cloud-nav-heading"><span>{heading}</span>{subheading ? <small className="uk-text-meta uk-display-block">{subheading}</small> : null}</div> }
export function SideNavSection({ title, children }: { title: string; children: ReactNode }) { return <div className="kora-cloud-nav-section"><div className="kora-cloud-nav-heading">{title}</div>{children}</div> }
export function SideNavItem({ label, icon: Icon, isSelected, onClick, endContent }: { label: string; icon?: ComponentType<{ size?: number }>; isSelected?: boolean; onClick?: () => void; endContent?: ReactNode }) { return <button type="button" className="kora-cloud-nav-item" data-selected={isSelected} onClick={onClick}>{Icon ? <Icon size={16} /> : null}<span>{label}</span>{endContent ? <span className="uk-margin-auto-left">{endContent}</span> : null}</button> }
export function Text({ children, display, weight, type, size, maxLines }: { children: ReactNode; display?: string; weight?: string; type?: string; size?: string; maxLines?: number }) { return <span className={cn(display === 'block' && 'uk-display-block', weight === 'bold' && 'uk-text-bold', weight === 'semibold' && 'uk-text-semibold', type === 'supporting' && 'uk-text-meta', size === 'sm' && 'uk-text-small', maxLines ? 'uk-text-truncate' : false)}>{children}</span> }
type TextInputProps = Omit<React.InputHTMLAttributes<HTMLInputElement>, 'onChange' | 'size'> & { isLabelHidden?: boolean; label?: string; size?: string; hasClear?: boolean; onChange?: (value: string) => void }
export function TextInput({ onChange, size: _size, ...props }: TextInputProps) { return <input {...props} onChange={event => onChange?.(event.target.value)} className={cn('uk-input', props.className)} /> }
export function Button({ label, icon, variant = 'default', isLoading, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { label?: string; icon?: ReactNode; variant?: Variant; size?: string; isLoading?: boolean }) { return <button {...props} disabled={isLoading || props.disabled} className={cn('uk-button', variant === 'destructive' ? 'uk-button-danger' : variant === 'secondary' || variant === 'outline' || variant === 'ghost' ? 'uk-button-default' : 'uk-button-primary', props.className)}>{icon}{isLoading ? 'Loading…' : label ?? props.children}</button> }
export function Badge({ label, variant = 'default' }: { label?: ReactNode; variant?: Variant | 'success' | 'error' | 'info' }) { return <span className={cn('uk-label', variant === 'destructive' || variant === 'error' ? 'uk-label-danger' : (variant === 'warning' || variant === 'outline') && 'uk-label-warning')}>{label}</span> }
export function StatusDot({ label, variant = 'neutral' }: { label?: string; variant?: string }) { return <span className="uk-flex uk-flex-middle uk-grid-small"><i className={cn('uk-badge', variant === 'success' && 'uk-background-success', variant === 'danger' && 'uk-background-danger')} />{label}</span> }
export function Card({ children, ...props }: HTMLAttributes<HTMLElement>) { return <section {...props} className={cn('uk-card uk-card-default', props.className)}>{children}</section> }
export function Table<T extends Record<string, unknown>>({ data, columns }: { data: T[]; columns: Array<{ key: keyof T | string; header: string; width?: string | number; align?: string; renderCell?: (row: T) => ReactNode }>; density?: string; dividers?: string; hasHover?: boolean; textOverflow?: string }) { return <div className="uk-overflow-auto"><table className="kora-cloud-table"><colgroup>{columns.map(c => <col key={String(c.key)} style={columnStyle(c.width)} />)}</colgroup><thead><tr>{columns.map(c => <th key={String(c.key)} style={{textAlign: c.align === 'end' ? 'right' : c.align === 'center' ? 'center' : 'left'}}>{c.header}</th>)}</tr></thead><tbody>{data.map((row, i) => <tr key={i}>{columns.map(c => <td key={String(c.key)} style={{textAlign: c.align === 'end' ? 'right' : c.align === 'center' ? 'center' : 'left'}}>{c.renderCell ? c.renderCell(row) : String(row[c.key as keyof T] ?? '')}</td>)}</tr>)}</tbody></table></div> }
function columnStyle(width?: string | number): React.CSSProperties | undefined { if (typeof width === 'string' && width.startsWith('px:')) return {width: `${width.slice(3)}px`}; if (typeof width === 'string' && width.startsWith('fr:')) return {width: `${width.slice(3)}fr`}; return typeof width === 'number' ? {width} : undefined }
export function pixel(value: number) { return `px:${value}` }
export function proportional(value: number) { return `fr:${value}` }
export type TableColumn<T> = { key: keyof T | string; header: string; width?: string | number; align?: string; renderCell?: (row: T) => ReactNode }
