- doctype: Grant Award
  role: NGO and Grant Management Operator
  can_read: true
  can_write: true
  can_create: true
  can_delete: false
  can_submit: true
- doctype: Grant Award
  role: NGO and Grant Management Reviewer
  can_read: true
  can_write: true
  can_create: false
  can_delete: false
  can_submit: true
- doctype: Grant Award
  role: NGO and Grant Management Administrator
  can_read: true
  can_write: true
  can_create: true
  can_delete: true
  can_submit: true
- doctype: Grant Budget
  role: NGO and Grant Management Operator
  can_read: true
  can_write: true
  can_create: true
  can_delete: false
- doctype: Program Activity
  role: NGO and Grant Management Reviewer
  can_read: true
  can_write: true
  can_create: true
  can_delete: false
