name: Professional Services and Timesheets Workflow
document_type: Engagement
is_active: true
workflow_state_field: status

states:
  - state: draft
    doc_status: 0
    allow_edit: Professional Services and Timesheets Operator, Professional Services and Timesheets Administrator
    style: default
  - state: active
    doc_status: 0
    allow_edit: Professional Services and Timesheets Reviewer, Professional Services and Timesheets Administrator
    style: info
  - state: at_risk
    doc_status: 0
    allow_edit: Professional Services and Timesheets Reviewer, Professional Services and Timesheets Administrator
    style: info
  - state: complete
    doc_status: 0
    allow_edit: Professional Services and Timesheets Reviewer, Professional Services and Timesheets Administrator
    style: info
  - state: closed
    doc_status: 1
    allow_edit: Professional Services and Timesheets Reviewer, Professional Services and Timesheets Administrator
    style: success

transitions:
  - action: Advance
    from: draft
    to: active
    allowed: Professional Services and Timesheets Operator, Professional Services and Timesheets Reviewer, Professional Services and Timesheets Administrator
  - action: Advance
    from: active
    to: at_risk
    allowed: Professional Services and Timesheets Operator, Professional Services and Timesheets Reviewer, Professional Services and Timesheets Administrator
  - action: Advance
    from: at_risk
    to: complete
    allowed: Professional Services and Timesheets Operator, Professional Services and Timesheets Reviewer, Professional Services and Timesheets Administrator
  - action: Advance
    from: complete
    to: closed
    allowed: Professional Services and Timesheets Operator, Professional Services and Timesheets Reviewer, Professional Services and Timesheets Administrator
