name: Small Business Operations Workflow
document_type: Sales Commitment
is_active: true
workflow_state_field: status

states:
  - state: new
    doc_status: 0
    allow_edit: Small Business Operations Operator, Small Business Operations Administrator
    style: default
  - state: qualified
    doc_status: 0
    allow_edit: Small Business Operations Reviewer, Small Business Operations Administrator
    style: info
  - state: quoted
    doc_status: 0
    allow_edit: Small Business Operations Reviewer, Small Business Operations Administrator
    style: info
  - state: accepted
    doc_status: 0
    allow_edit: Small Business Operations Reviewer, Small Business Operations Administrator
    style: info
  - state: fulfilled
    doc_status: 0
    allow_edit: Small Business Operations Reviewer, Small Business Operations Administrator
    style: info
  - state: closed
    doc_status: 1
    allow_edit: Small Business Operations Reviewer, Small Business Operations Administrator
    style: success

transitions:
  - action: Advance
    from: new
    to: qualified
    allowed: Small Business Operations Operator, Small Business Operations Reviewer, Small Business Operations Administrator
  - action: Advance
    from: qualified
    to: quoted
    allowed: Small Business Operations Operator, Small Business Operations Reviewer, Small Business Operations Administrator
  - action: Advance
    from: quoted
    to: accepted
    allowed: Small Business Operations Operator, Small Business Operations Reviewer, Small Business Operations Administrator
  - action: Advance
    from: accepted
    to: fulfilled
    allowed: Small Business Operations Operator, Small Business Operations Reviewer, Small Business Operations Administrator
  - action: Advance
    from: fulfilled
    to: closed
    allowed: Small Business Operations Operator, Small Business Operations Reviewer, Small Business Operations Administrator
